#!/bin/bash
swaymsg "workspace 1"
swaymsg "exec footclient distrobox enter arch -- /usr/bin/fish"
swaymsg "exec firefox"
sleep 5s
swaymsg "splitv"
swaymsg "layout tabbed"
swaymsg "resize grow width 20ppt"
