#!/bin/bash
swaymsg "workspace 1"
swaymsg "exec footclient distrobox enter arch -- /usr/bin/fish"
swaymsg "exec flatpak run org.mozilla.firefox"
swaymsg "exec flatpak run io.github.NhekoReborn.Nheko"
sleep 5s
swaymsg "splitv"
swaymsg "layout tabbed"
swaymsg "resize grow width 20ppt"
