#!/bin/sh

export TERMINAL="foot"
export BROWSER="flatpak run org.mozilla.firefox"
export EDITOR="nvim"

export SDL_VIDEODRIVER="wayland"
export QT_QPA_PLATFORM="wayland"
export GDK_BACKEND="wayland,x11"
export _JAVA_AWT_WM_NONREPARENTING=1

export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1
export MOZ_ACCELERATED=1

