#!/bin/bash
swaymsg "exec flatpak run org.mozilla.firefox"
swaymsg "exec footclient distrobox enter arch -- /usr/bin/fish"
swaymsg "exec flatpak run im.riot.Riot --enable-features=UseOzonePlatform --ozone-platform=wayland"
sleep 5s
swaymsg "splitv"
swaymsg "layout tabbed"
swaymsg "resize grow width 35ppt"
